
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 06 16:32:43 EST 2016
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int POW = 14;
  public static final int GE = 22;
  public static final int CAR = 30;
  public static final int INTEGER = 32;
  public static final int CDR = 31;
  public static final int LPAREN = 2;
  public static final int SEMI = 6;
  public static final int PAIRCHECK = 29;
  public static final int MINUS = 10;
  public static final int CHARACTER = 35;
  public static final int RPAREN = 3;
  public static final int LT = 20;
  public static final int BOOL = 34;
  public static final int COMMA = 7;
  public static final int BAND = 15;
  public static final int DIV = 12;
  public static final int BNOT = 17;
  public static final int PLUS = 9;
  public static final int ASSIGN = 27;
  public static final int LE = 21;
  public static final int EOF = 0;
  public static final int LNOT = 24;
  public static final int LAND = 25;
  public static final int error = 1;
  public static final int MUL = 11;
  public static final int LOR = 26;
  public static final int MOD = 13;
  public static final int NEQ = 23;
  public static final int PAIR = 28;
  public static final int EQ = 18;
  public static final int REAL = 33;
  public static final int NEG = 8;
  public static final int BOR = 16;
  public static final int LBRACE = 4;
  public static final int VARIABLE = 37;
  public static final int RBRACE = 5;
  public static final int STRING = 36;
  public static final int GT = 19;
}

