
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Dec 06 12:15:59 EST 2016
//----------------------------------------------------

package smpl.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MOD = 13;
  public static final int NEG = 8;
  public static final int PLUS = 9;
  public static final int RBRACE = 5;
  public static final int RPAREN = 3;
  public static final int CHARACTER = 23;
  public static final int SEMI = 6;
  public static final int POW = 14;
  public static final int VARIABLE = 25;
  public static final int LPAREN = 2;
  public static final int LBRACE = 4;
  public static final int CAR = 18;
  public static final int CDR = 19;
  public static final int STRING = 24;
  public static final int COMMA = 7;
  public static final int EOF = 0;
  public static final int PAIRCHECK = 17;
  public static final int DIV = 12;
  public static final int MINUS = 10;
  public static final int error = 1;
  public static final int ASSIGN = 15;
  public static final int BOOL = 22;
  public static final int INTEGER = 20;
  public static final int REAL = 21;
  public static final int MUL = 11;
  public static final int PAIR = 16;
}

